/**
 * spaceGuide — the briefing notation drops into a synced folder so a local CLI
 * agent (Claude Code, Cursor, Codex, …) knows what it is looking at.
 *
 * A pulled folder is just a pile of Markdown; nothing in it says "these files
 * are a notation Space", that a folder holding `_form.md` is a fillable form,
 * that `[[wiki-links]]` resolve, or that a passage can carry comments. An agent
 * that doesn't know invents its own conventions and the push brings back
 * something the app can't render properly.
 *
 * So {@link pull} writes {@link GUIDE_FILENAMES} — the two names CLI agents load
 * by themselves — into the folder root. They are **tooling, not content**:
 *
 *   - every generated guide starts with {@link GUIDE_MARKER}, and the push
 *     strips exactly the marked files back out ({@link isGeneratedGuide}), so
 *     the Space never gains an `AGENTS.md` it didn't ask for;
 *   - a guide is only written for a name the Space does NOT itself use, so a
 *     real `AGENTS.md` page in the Space always wins and round-trips normally;
 *   - delete the marker line and the file stops being ours — it becomes an
 *     ordinary file the next push carries into the Space.
 *
 * The text is regenerated on every pull, so it always describes the Space in
 * front of it (name, encrypted or not, which form folders exist).
 */

/**
 * First line of every generated guide. The push looks for it (near the start of
 * the file only) to tell "our briefing" from a file the user actually wants.
 */
export const GUIDE_MARKER = '<!-- notation:folder-guide'

/**
 * Root-level names a generated guide may occupy — the files CLI agents pick up
 * without being told: `AGENTS.md` (the cross-tool convention) and `CLAUDE.md`
 * (Claude Code), the latter a pointer at the former so there is one source of
 * truth.
 */
export const GUIDE_FILENAMES = ['AGENTS.md', 'CLAUDE.md'] as const

/** What the guide says about THIS Space. */
export interface GuideContext {
  /** Display name of the Space (falls back to its id). */
  spaceName: string
  /** Zero-knowledge Space? Then the folder holds decrypted plaintext. */
  encrypted: boolean
  /** Folders that hold a `_form.md` template, i.e. render as Forms. */
  formFolders: string[]
  /** How many files the pull wrote (context for an agent sizing the corpus). */
  fileCount: number
}

/** One file to drop into the folder root. */
export interface GuideFile {
  name: string
  content: string
}

/**
 * True when `bytes` look like a guide WE generated: the marker appears in the
 * first few hundred bytes. Deliberately a prefix check — a Markdown page that
 * merely quotes the marker deep in its body stays a normal file.
 */
export function isGeneratedGuide(bytes: Uint8Array): boolean {
  const head = new TextDecoder().decode(bytes.subarray(0, 512))
  return head.includes(GUIDE_MARKER)
}

/** True for a root-level path that a generated guide is allowed to occupy. */
export function isGuideName(path: string): boolean {
  return (GUIDE_FILENAMES as readonly string[]).includes(path)
}

/**
 * The guide files for a Space. `AGENTS.md` carries the whole briefing;
 * `CLAUDE.md` is a three-line pointer at it (Claude Code follows the `@`
 * import), so editing one file keeps both tools in sync.
 */
export function guideFiles(ctx: GuideContext): GuideFile[] {
  return [
    { name: 'AGENTS.md', content: agentsGuide(ctx) },
    { name: 'CLAUDE.md', content: claudePointer(ctx) },
  ]
}

const header = (title: string) => `${GUIDE_MARKER} v1 — generated by notation on every pull. Not part of the Space: the push strips it back out. Delete this line to turn the file into real content. -->\n\n# ${title}\n`

function claudePointer(ctx: GuideContext): string {
  return (
    header(`notation Space — ${ctx.spaceName}`) +
    `
This folder is a checkout of a **notation** Space. The full briefing — what the
Space is, which Markdown features render, how Forms work, and what the push does
with your changes — lives in \`AGENTS.md\`:

@AGENTS.md
`
  )
}

function agentsGuide(ctx: GuideContext): string {
  const forms =
    ctx.formFolders.length > 0
      ? `This Space currently has ${ctx.formFolders.length} form folder${ctx.formFolders.length === 1 ? '' : 's'}: ` +
        ctx.formFolders.map((f) => `\`${f}/\``).join(', ') +
        '.\n'
      : 'This Space has no form folders yet — create one by adding a `_form.md` to a folder.\n'

  const crypto = ctx.encrypted
    ? `
> **This Space is end-to-end encrypted.** The server only ever holds ciphertext;
> the files in this folder were decrypted in the browser and written here in the
> clear on purpose, so local tools can work on them. Treat the folder as
> sensitive: don't copy it somewhere public, and don't commit it to a remote
> repository. The push re-encrypts everything in the browser again.
`
    : `
> This Space is stored as plain files with per-Space git history. Every file the
> push writes lands in that history like any other edit.
`

  return (
    header(`notation Space — ${ctx.spaceName}`) +
    `
You are working in a local checkout of a **notation** Space: a self-hosted notes
and file workspace (flat files, git history per Space, share links, comments,
forms, an MCP server). Someone pulled the Space into this folder so local tools
could edit it, and will push the result back through a reviewed diff.

There are currently **${ctx.fileCount} file${ctx.fileCount === 1 ? '' : 's'}** here from the Space.
${crypto}
## How this folder syncs

- **Nothing here is live.** A human clicks *Pull* (Space → folder) and *Push*
  (folder → Space) in the app. The push shows a change preview — new, modified,
  moved, deleted, conflicting — and applies it only on confirm.
- **Deletions are opt-in.** Removing a file here proposes a deletion; the human
  has to tick a box for it to happen. Don't rely on a delete going through.
- **Moves are detected.** Renaming or moving a file is recognised as a move (by
  content, or by an unchanged filename), and the Space performs a real move — so
  the page keeps its comments, reactions and history instead of arriving as a
  brand-new file.
- **Conflicts resolve folder-wins**, and are listed before anything is applied.
- **Ignored on both sides**: every dotfile and dot-directory (\`.git\`, \`.env\`,
  the \`.notation-sync.json\` manifest) and any \`node_modules/\`. Scratch files
  you leave outside those names WILL be proposed for the Space — clean up after
  yourself, or hide the file behind a leading dot.
- **This briefing never travels.** \`AGENTS.md\` and \`CLAUDE.md\` are regenerated
  on every pull and stripped from every push.

## What renders in notation

Markdown is the native format (\`.md\`, \`.markdown\`, \`.mdx\`). On top of
CommonMark + GFM the viewer supports:

| Feature | Syntax |
|---|---|
| Wiki-links | \`[[other-page]]\`, \`[[other-page#section]]\`, \`[[other-page\\|label]]\` |
| Heading anchors | every heading is linkable; ids are slugified from the text |
| Mermaid diagrams | a fenced code block with the \`mermaid\` language |
| Math | \`$inline$\` and \`$$display$$\` (KaTeX) |
| Code | fenced blocks, 30+ languages, highlighted |
| Task lists, tables, footnotes | standard GFM |

Wiki-links resolve against the Space's own file set, so keep link targets in
step when you rename a page. Raw HTML is sanitised before it renders — script
tags, event handlers and inline styles are dropped, so don't reach for them.

Other file types the app can display without conversion: images, PDF, video,
audio, \`.xlsx\`/\`.ods\`/\`.csv\` (table view), \`.docx\` (converted to prose), and
any source file (highlighted). Everything else is offered as a download.

## Forms

A **Form** is simply a folder that contains a file named \`_form.md\`. The app
then renders that folder as a fillable form instead of a file list: people
submit entries, and each submission is stored as a sibling Markdown file in the
same folder.

${forms}
### Authoring \`_form.md\`

It is ordinary Markdown with two special rules:

- the first \`# Heading\` is the form title;
- **every line containing a \`[type]\` tag becomes a field**, labelled by the text
  before the tag. A run of underscores (\`______\`) is an optional "fill in the
  blank" placeholder and is stripped. If the field line carries no label, the
  previous non-empty line is used as one (handy for big text fields).

Modifiers after the tag: \`(required)\` or \`(*)\`, and \`(default: value)\`.
Choices for \`select\`/\`buttons\`/\`multiselect\` go inline — \`[select: low, high]\`
— or as a trailing group \`(low, high)\`. \`[slider: min, max, step]\` defaults to
\`0, 100, 1\`; \`[rating: levels]\` defaults to 5 stars.

| Type | Aliases | Input |
|---|---|---|
| \`string\` | str, line | single-line text |
| \`text\` | textarea, multiline, paragraph | multi-line text |
| \`integer\` | int, whole | whole number |
| \`number\` | num, float, decimal | decimal number |
| \`bool\` | boolean, checkbox, check, yesno | yes/no checkbox |
| \`date\` / \`time\` / \`datetime\` | timestamp | pickers |
| \`select\` | choice, dropdown, enum, option | single choice, dropdown |
| \`buttons\` | radio, toggle, choices, pills | single choice, pills |
| \`multiselect\` | multi, checklist, tags, checkboxes | multiple choice |
| \`smiley\` | smileys, mood, emoji | 1..5 mood scale |
| \`rating\` | stars, star | 1..N stars |
| \`slider\` | range | numeric range |
| \`image\` | images, photo, picture, pic | image upload |
| \`email\` | mail | email address |
| \`url\` | link | URL |

An unknown type falls back to \`string\`. Field keys are derived from the label
(lowercased, umlauts folded: ä→ae, ö→oe, ü→ue, ß→ss), so give fields distinct
labels. The **first** field labels each submission in the entry list — put the
most identifying one first.

Example — \`standup/_form.md\`:

\`\`\`markdown
# Daily standup

Name: ______ [string] (required)
Date: ______ [date] (required)
Mood: ______ [smiley]
Focus today: ______ [select: feature, bug, review, ops]
Confidence: ______ [slider: 0, 10, 1]

What did you do?
______ [text]
\`\`\`

**Don't hand-write entries.** Submission files carry a \`notation_entry: true\`
frontmatter flag and are created by the app when someone fills the form in.
Editing the template is your job; inventing entries is not.

## Comments, reactions and why moves matter

Readers select a passage in the app and pin a **comment** or an **emoji
reaction** to that exact quote. The anchor is stored as the quoted text plus a
short window of the surrounding text, not a line number — so it survives ordinary
edits above and around it.

What breaks an anchor is rewriting the quoted passage itself, or moving the file
in a way the app can't recognise as a move. Two habits keep annotations intact:

1. **Move and rename files as such** — one operation, content unchanged. A move
   plus a heavy rewrite in the same push is harder to match and may orphan the
   thread (the app will then ask a human where it went).
2. **Leave quoted passages alone when you can.** If you must rewrite one,
   rewording around it is safer than replacing it wholesale.

## Working style

- Match the surrounding documents: this is someone's knowledge base, not a
  codebase. Keep headings, tone and structure consistent with the neighbours.
- Prefer editing pages in place over restructuring the tree. A reshuffle
  produces a large, hard-to-review push.
- Don't create \`README\`-style meta files unless asked — the Space is read in
  the app, not on a repository page.
- Empty folders left behind by a push are removed automatically.
`
  )
}
